# Destination vCenter details
vcenter_hostname: "198.51.100.10"
vcenter_username: "automation-svc"
vcenter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          EXAMPLE_ENCRYPTED_VALUE_REDACTED_FOR_PUBLIC_REPOSITORY
my_datacenter: "CS PRD"
my_datastore: "ESX180 Restricted Datastore Cluster (CS)"
my_folder: "/CS PRD/vm/Automation/Templates"
my_cluster: "cluster05.example.com"