---
# vars file
source_vcenter_hostname: "198.51.100.10"
source_vcenter_username: "automation-svc"
source_vcenter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          EXAMPLE_ENCRYPTED_VALUE_REDACTED_FOR_PUBLIC_REPOSITORY
source_datacenter: "CS NON-PROD"

export_path: "/tmp"  # Path where the OVF/OVA will be exported
turn_into_template: true
source_vm_suffix: "-Restricted"