---
# vars file for WinInstallSplunk
capsule: csstsrvlvcap152.services.stamp.tsa.dhs.gov
tools_url: "https://{{ capsule }}/pulp/content/STA/Library/custom/WindowsTeam/Software/"
tanium_agent: Tanium_7.4.9.1046