---
# tasks file for InstallFlexera
- name: Install and run the custom facts on Windows System
  ansible.builtin.include_role:
    name: ENTERPRISE.Windows.WinFacts

- name: Grab the capsule server name
  ansible.builtin.set_fact:
    capsule: "{{ ansible_local['vmInfo']['capsule'] }}"

# - name: "Grab the variables for DataCenter"
#   ansible.builtin.include_vars: Configure_{{ DataCenter }}.yml

- name: Download Software to install
  ansible.windows.win_get_url:
    dest: C:\temp
    url: "{{ tools_url }}"
    url_timeout: 60
    validate_certs: no

- name: Unzip Software
  community.windows.win_unzip:
    src:  "{{ win_stage_dir }}/{{ win_flex_zip }}"
    dest: "{{ win_stage_dir }}"

- name: Stage the appropriate mgssetup.ini file for AJ
  vars:
    Beacon: "{{ aj_beacon }}"
  ansible.builtin.template:
    src: mgssetup.ini.j2
    dest: "{{ win_stage_dir }}/Flexera/mgssetup.ini"
  when: ansible_local['vmInfo']['datacenter'] == "AJNON" or ansible_local['vmInfo']['datacenter'] == "AJPRD"

- name: Stage the appropriate mgssetup.ini file for CS
  vars:
    Beacon: "{{ cs_beacon }}"
  ansible.builtin.template:
    src: mgssetup.ini.j2
    dest: "{{ win_stage_dir }}/Flexera/mgssetup.ini"
  when: ansible_local['vmInfo']['datacenter'] == "CSNON" or ansible_local['vmInfo']['datacenter'] == "CSPRD"

- name: Run the Flexera batch installer
  ansible.windows.win_command: C:\temp\Flexera\Install.bat

- name: Delete setup files
  ansible.windows.win_file:
    path: "{{ win_stage_dir }}/Flexera"
    state: absent
  when: cleanup == "yes"

- name: Pause 30 seconds to make sure the registry keys gets created
  ansible.builtin.pause:
    seconds: 30

- name: Run the WinRegistryInfo role
  ansible.builtin.include_role:
    name: ENTERPRISE.Windows.WinRegistryInfo
  vars:
    registry_key_path: 'HKLM:\SOFTWARE\WOW6432Node\ManageSoft Corp\ManageSoft\Common\DownloadSettings\{088744b6-bc64-4b12-8bc8-eddfdb77dd57}'
    registry_key_name: Host

- name: Check if the registry keys exist
  ansible.builtin.assert:
    that: current_version.exists == true
    fail_msg: "Flexera is not setup to talk to the beacons"
    success_msg: "Flexera is setup and working as expected"
  ignore_errors: yes