---
galaxy_info:
  author: ENTERPRISE Automation Team
  description: Puts Exchange servers into maintenance mode
  company: ENTERPRISE Automation Team
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - 2016
        - 2019
        - 2022
        - 2025
  galaxy_tags:
    - exchange
    - exchange-2016
    - exchange-2019
    - exchange-se
    - maintenance
    - cluster

dependencies: []
