---
# vars file for TemplateRole
nexus_url: https://csstsrvlvsat151.services.stamp.tsa.dhs.gov/pulp/content/STA/Library/custom/STAMPLinuxBinaries/Software/
repo_loc: pulp/content/STA/Library/custom/STAMPLinuxBinaries/Software/
netbackup_tar: RedHat_NBU.tar
stage_dir: /var/tmp/staging
root_user: root
root_group: root