---
_hosts: '{{ my_vct_servername }}'
my_cluster: csstsrvlpesx140
my_folder: Linux/TIM/SIT
my_datacenter: CS PRD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: "TIM Trusted (NON)"
my_netmask: 255.255.255.0
my_gateway_address: 10.2.28.1
my_dnsserver1: 10.2.4.129
my_dnsserver2: 10.2.8.129
my_dns_domain: dev.example.com
my_datastore: ESX140 Trusted Datastore Cluster (CS)