---
_hosts: '{{ my_vct_servername }}'
my_cluster: ajstsrvlpesx150
my_folder: Linux/TIM/PRD
my_datacenter: AJ PRD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: TIM Semi-Trusted (PRD)
my_netmask: 255.255.255.0
my_gateway_address: 192.168.78.9
my_dnsserver1: 192.168.75.61
my_dnsserver2: 192.168.75.62
my_dns_domain: dmz.example.com
my_datastore: Trusted Datastore Cluster (AJ)