---
_hosts: '{{ my_vct_servername }}'
my_cluster: cluster01.example.com
my_folder: Linux/ENTERPRISE
my_datacenter: AJ NON-PROD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: GSS Trusted (NON)
my_netmask: 255.255.255.0
my_gateway_address: 198.51.100.20
my_dnsserver1: 10.2.8.129
my_dnsserver2: 10.2.8.132
my_dns_domain: dev.example.com
my_datastore: Trusted Datastore Cluster (AJ)