---
_hosts: '{{ my_vct_servername }}'
my_cluster: csstsrvlpesx180
my_folder: Linux/TIM/PRD
my_datacenter: CS PRD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: TIM Restricted (PRD)
my_netmask: 255.255.254.0
my_gateway_address: 10.0.122.1
my_dnsserver1: 10.0.4.129
my_dnsserver2: 10.0.8.129
my_dns_domain: cvp.cs
my_datastore: ESX180 Restricted Datastore Cluster (CS)
my_template: RHEL8_CRED_Template-Restricted