---
_hosts: '{{ my_vct_servername }}'
my_cluster: cluster04.example.com
my_folder: Linux/ENTERPRISE
my_datacenter: CS PRD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: GSS Trusted (PRD)
my_netmask: 255.255.254.0
my_gateway_address: 198.51.100.10
my_dnsserver1: 10.0.4.129
my_dnsserver2: 10.0.4.132
my_dns_domain: cvp.cs
my_datastore: ESX150 Trusted Datastore Cluster (CS)