---
my_vct_servername: AJSTSRVWVBLD253
my_cluster: cluster01.example.com
my_folder: Linux/Testing
my_datacenter: AJ NON-PROD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: aj-stmp-ppd-wininf
my_netmask: 255.255.255.0
my_gateway_address: 198.51.100.20
my_dnsserver1: 198.51.100.10
my_dnsserver2: 198.51.100.20
my_dns_domain: services.ppdstamp.example.com
my_datastore: Trusted Datastore Cluster (AJ)
my_ip_address: 198.51.100.20
old_template_name: Win19OneDiskTmpl
new_template_name: "Windows2019_{{ timestamp }}"
timestamp: "{{ ansible_date_time.date}}-{{ ansible_date_time.time}}"