---
_hosts: '{{ my_vct_servername }}'
my_cluster: csssnonlpesx50.dev.example.com
my_folder: Linux/ENTERPRISE
my_datacenter: CS NON-PROD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: cs-stmp-ppd-paas
my_netmask: 255.255.254.0
my_gateway_address: 172.26.214.1
my_dnsserver1: 172.26.157.51
my_dnsserver2: 172.27.157.51
my_dns_domain: services.ppdstamp.example.com
my_datastore: Trusted Datastore Cluster (CS)