---
_hosts: '{{ my_vct_servername }}'
my_cluster: ajstsrvlpesx150
my_folder: Linux/ENTERPRISE
my_datacenter: AJ PRD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: aj-stmp-prd-devservices
my_netmask: 255.255.255.0
my_gateway_address: 172.27.65.1
my_dnsserver1: 172.26.57.51
my_dnsserver2: 172.27.57.51
my_dns_domain: services.stamp.tsa.dhs.gov
my_datastore: Trusted Datastore Cluster (AJ)