---
_hosts: '{{ my_vct_servername }}'
my_cluster: csstsrvlpesx150
my_folder: Linux/PIPE
my_datacenter: CS PRD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: PI-PRD-TRUST-CS
my_netmask: 255.255.255.0
my_gateway_address: 10.111.50.1
my_dnsserver1: 172.26.57.52
my_dnsserver2: 172.27.57.52
my_dns_domain: pi.example.com
my_datastore: ESX150 Trusted Datastore Cluster (CS)