---
_hosts: '{{ my_vct_servername }}'
my_cluster: ajssnonlpesx50.dev.example.com
my_folder: Linux/SG/STG
my_datacenter: AJ NON-PROD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: SG Restricted (TST)
my_netmask: 255.255.255.0
my_gateway_address: 10.20.7.1
my_dnsserver1: 10.20.1.80
my_dnsserver2: 10.20.1.85
my_dns_domain: test.tvc.tsa.dhs.gov
my_datastore: Trusted Datastore Cluster (AJ)