---
_hosts: '{{ my_vct_servername }}'
my_cluster: ajstsrvlpesx140
my_folder: Linux/SG
my_datacenter: AJ PRD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: SG Semi-Trusted (NON 520)
my_netmask: 255.255.255.0
my_gateway_address: 10.20.2.1
my_dnsserver1: 10.20.1.85
my_dnsserver2: 10.20.1.80
my_dns_domain: test.tvc.tsa.dhs.gov
my_datastore: ESX140 Trusted Datastore Cluster (AJ)