---
# tasks file for AddCpuRamToHost
- name: Get Datacenter Information
  ansible.builtin.include_role:
    name: GetDatacenterInfo
  when: my_datacenter is not defined

- name: Run only if the VMLOCATION matches my_datacenter
  debug:
    msg: "Skipping this vcenter server"
  when: VMLOCATION != my_datacenter

- name: Get Folder Information
  ansible.builtin.include_role:
    name: GetFolderInfo
  when: my_folder is not defined

- name: Main Block
  block:
  - name: Power Off Virtual Machine
    ansible.builtin.include_role:
      name: PowerOffVM
    when: areyousure_shutdown == "yes"

  - name: Update CPU and Memory
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname | default(omit) }}" 
      username: "{{ vcenter_username | default(omit) }}"
      password: "{{ vcenter_password | default(omit) }}"
      validate_certs: false
      name: "{{ my_vct_servername | upper }}"
      datacenter: "{{ my_datacenter }}"
      folder: "{{ my_folder }}"
      hardware:
        hotadd_cpu: true
        hotadd_memory: true
        memory_mb: "{{ my_memory_mb | default(omit) }}"
        num_cpus:  "{{ my_num_cpus  | default(omit) }}"
        scsi: paravirtual
      state: present
    delegate_to: localhost
    register: ReduceCpuMem
  
  - name: Power On Virtual Machine
    ansible.builtin.include_role:
      name: PowerOnVM

  when: VMLOCATION == my_datacenter and areyousure_shutdown == "yes"

