# tasks file for Create_vm- name: Create a virtual machine on given ESXi hostname
- name: Convert Template to Virtual Machine
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname | default(omit) }}" 
    username: "{{ vcenter_username | default(omit) }}"
    password: "{{ vcenter_password | default(omit) }}"
    # This is hostname of particular ESXi server on which user wants VM to be deployed
    esxi_hostname: "{{ esxi_hostname | default(omit) }}"
    validate_certs: false

    name: "{{ my_vct_servername | default('RHEL87_CRED_Template') }}"
    datacenter: "CS NON-PROD"
    folder: "Linux/Testing"
    guest_id: rhel8_64Guest
    disk:
    - size_gb: 250
      type: thin
      datastore: "Trusted Datastores (ESX50)"
    hardware:
      boot_firmware: "efi"
      hotadd_cpu: true
      hotadd_memory: true
      memory_mb: 8192
      num_cpus: 4
      scsi: paravirtual
    networks:
    - name: "{{ my_network_name | default('VM - GSS Quarantine (LACP)') }}"
      connected: true
      start_connected: true
      ip: "{{ my_ip_address | default('172.26.60.254') }}"
      netmask: "{{ my_netmask | default('255.255.255.0') }}"
      gateway: "{{ my_gateway_address | default('172.26.60.1') }}"
      device_type: vmxnet3
      type: static
    template: "{{ my_template }}"
    state: "{{ my_state | default('poweredon') }}"
  delegate_to: localhost
  register: deploy_vm

- name: Wait for the host to finish restarting 
  ansible.builtin.pause:
    minutes: 1
