---
# - name: Lookup login and password
#   ansible.builtin.set_fact:
#     login:  "{{ lookup('ansible.builtin.csvfile', 'csssnonlpesx50.dev.example.com file=newvms col=1') }}"
#     passwd: "{{ lookup('ansible.builtin.csvfile', 'csssnonlpesx50.dev.example.com file=newvms col=2') }}"
#   delegate_to: localhost
- name: Download the CSV file
  ansible.builtin.get_url:
    url: https://satellite.example.com/pulp/content/STA/Library/custom/STAMPLinuxBinaries/Configuration/serverdetails.csv
    dest: /var/tmp/serverdetails.csv
    mode: '0644'
    validate_certs: no
  delegate_to: localhost

- name: Read CSV file
  community.general.read_csv:
    path: /var/tmp/serverdetails.csv
  register: newvms_list
  delegate_to: localhost

- name: block to build VMs from CSV
  block:
  # tasks file for Create_vm- name: Create a virtual machine on given ESXi hostname
  - name: Create shell vm
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname | default(omit) }}" 
      username: "{{ vcenter_username | default(omit) }}"
      password: "{{ vcenter_password | default(omit) }}"
      # This is hostname of particular ESXi server on which user wants VM to be deployed
      #esxi_hostname: "{{ esxi_hostname | default(omit) }}"
      cluster: "{{ my_cluster }}"
      validate_certs: false

      name: "{{ item.my_vct_servername }}"
      datacenter: "{{ my_datacenter }}"
      folder: "{{ my_folder }}"
      guest_id: "{{ my_guest_id  }}"
      disk:
      - size_gb: 250
        type: eagerzeroedthick
        datastore: "{{ my_datastore }}"
      hardware:
        boot_firmware: "efi"
        hotadd_cpu: true
        hotadd_memory: true
        memory_mb: "{{ my_memory_mb_small  }}"
        num_cpus:  "{{ my_num_cpus_small }}"
        scsi: paravirtual
      networks:
      - name: "{{ my_network_name }}"
        connected: true
        start_connected: true
        ip: "{{ item.my_ip_address }}"
        netmask: "{{ my_netmask }}"
        gateway: "{{ my_gateway_address }}"
        device_type: vmxnet3
        type: static
      customization:
        hostname: "{{ my_hostname }}"
        dns_servers:
        - "{{ my_dnsserver1 }}"
        - "{{ my_dnsserver2 }}"
        dns_suffix:
        - "{{ my_dns_domain }}"
        domain: "{{ my_dns_domain }}"
      template: "{{ my_template }}"
      state: "{{ my_state }}"
      wait_for_ip_address: true
      wait_for_ip_address_timeout: 300
    delegate_to: localhost
    register: deploy_vm
    loop: "{{ newvms_list.list }}"
    when: item.my_datacenter == VMLOCATION
