---
- name: Run the Inventory Update on CS PRD
  ansible.builtin.uri:
    url: https://aap-controller.example.com/api/v2/inventory_sources/14/update/
    user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          EXAMPLE_ENCRYPTED_VALUE_REDACTED_FOR_PUBLIC_REPOSITORY
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          EXAMPLE_ENCRYPTED_VALUE_REDACTED_FOR_PUBLIC_REPOSITORY
    method: POST
    force_basic_auth: true
    return_content: false
    status_code: 202
    headers:
      Content-Type: application/json
    body:
    validate_certs: false