---
# vars file for InstallSplunk
#nexus_url: https://nexus.stamp.tsa.dhs.gov:9090/repository/STAMPLinuxBinaries/InstallFlexera/
nexus_url: https://satellite.example.com/pulp/content/STA/Library/custom/STAMPLinuxBinaries/Software/
repo_loc: pulp/content/STA/Library/custom/STAMPLinuxBinaries/Software/
win_repo_loc: pulp/content/STA/Library/custom/WindowsTeam/Software/
splunkforwarder_pkg: splunkforwarder-9.3.2.tar
stage_dir: /root
root_user: root
root_group: root
splunk_version: 9.3.2
splunk_install_bin: splunkInstall.sh
splunk_files:  [ "splunkInstall.sh", "splunkforwarder-9.3.2-d8bb32809498-Linux-x86_64.tgz", "tsoc_all_deploymentclient_ds02.zip", "splunkforwarder-9.3.2.tar" ]
splunk_path: /opt/splunkforwarder
splunk_owner: splkadm
splunk_group: splunk
reinstall: "no"
pkg_name: splunkforwarder-9.3.2-d8bb32809498-x64-release.msi