---
# - name: Lookup login and password
#   ansible.builtin.set_fact:
#     login:  "{{ lookup('ansible.builtin.csvfile', 'csssnonlpesx50.dev.example.com file=newvms col=1') }}"
#     passwd: "{{ lookup('ansible.builtin.csvfile', 'csssnonlpesx50.dev.example.com file=newvms col=2') }}"
#   delegate_to: localhost
- name: Download the CSV file
  ansible.builtin.get_url:
    url: "https://satellite.example.com/pulp/content/STA/Library/custom/STAMPLinuxBinaries/Configuration/{{ csv_name }}"
    dest: "/var/tmp/{{ csv_name }}"
    mode: '0644'
    validate_certs: no
  delegate_to: localhost

- name: Read CSV file
  community.general.read_csv:
    path: "/var/tmp/{{ csv_name }}"
  register: newvms_list
  delegate_to: localhost

- name: block to build VMs from CSV
  block:
  - name: Create shell vm
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname | default(omit) }}" 
      username: "{{ vcenter_username | default(omit) }}"
      password: "{{ vcenter_password | default(omit) }}"
      cluster: "{{ item.my_cluster }}"
      validate_certs: false
      annotation: "{{ annotation_text | default(omit) }}"
      name: "{{ item.my_vct_servername }}"
      datacenter: "{{ item.my_datacenter }}"
      folder: "{{ item.my_folder }}"
      disk:
      - size_gb: 250
        type: eagerzeroedthick
        datastore: "{{ item.my_datastore }}"
      hardware:
        boot_firmware: "efi"
        hotadd_cpu: true
        hotadd_memory: true
        memory_mb: "{{ item.my_memory_mb }}"
        num_cpus:  "{{ item.my_num_cpus }}"
        scsi: paravirtual
      networks:
      - name: "{{ item.my_network_name }}"
        connected: true
        start_connected: true
        ip: "{{ item.my_ip_address }}"
        netmask: "{{ item.my_netmask }}"
        gateway: "{{ item.my_gateway_address }}"
        device_type: vmxnet3
        type: static
      customization:
        hostname: "{{ item.my_hostname }}"
        dns_servers:
        - "{{ item.my_dnsserver1 }}"
        - "{{ item.my_dnsserver2 }}"
        dns_suffix:
        - "{{ item.my_dns_domain }}"
        domain: "{{ item.my_dns_domain }}"
      template: "{{ item.my_template }}"
      state: "{{ item.my_state }}"
      wait_for_ip_address: true
      wait_for_ip_address_timeout: 300
    delegate_to: localhost
    register: async_jobs
    loop: "{{ newvms_list.list }}"
    when: item.my_datacenter == VMLOCATION
    poll: 0 # trying this to increase the speed of building hosts
    async: 1200 # trying this to increase the speed of building hosts

- name: Debug the async_jobs variable if needed
  ansible.builtin.debug:
    var: async_jobs
    verbosity: 1

- name: Wait for all clone tasks to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ async_jobs.results }}"
  # loop_control:
  #   label: "{{ item.item }}"
  register: clone_results
  until: clone_results.finished
  retries: 100
  delay: 10
  when: item.ansible_job_id is defined

- name: Pass along the _hosts to the rest of the workflow if defined
  ansible.builtin.set_stats:
    data:
      _hosts: "{{ _hosts }}"
  when: _hosts is defined