---
- name: Create the facts.d directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    owner: root
    group: root
    mode: '0755'
    state: directory
- name: Deploy vmInfo fact
  ansible.builtin.copy:
    dest: /etc/ansible/facts.d/vmInfo.fact
    src: vmInfo.fact
    owner: root
    group: root
    mode: '0755'
- name: Get the local facts
  ansible.builtin.setup:
    filter: ansible_local