---
_hosts: '{{ my_vct_servername }}'
my_cluster: cluster04.example.com
my_folder: Linux/ENTERPRISE
my_datacenter: CS PRD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: VM - cs-stmp-prd-linuxinf
my_netmask: 255.255.255.0
my_gateway_address: 198.51.100.10
my_dnsserver1: 198.51.100.10
my_dnsserver2: 198.51.100.20
my_dns_domain: services.stamp.tsa.dhs.gov
my_datastore: Trusted Datastore Cluster (CS)