---
_hosts: '{{ my_vct_servername }}'
my_cluster: ajstsrvlpesx150
my_folder: Linux/SG/PRD
my_datacenter: AJ PRD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: VM - SG Trusted (PRD, 11)
my_netmask: 255.255.255.0
my_gateway_address: 10.10.0.1
my_dnsserver1: 10.10.0.20
my_dnsserver2: 10.10.0.32
my_dns_domain: tvc.tsa.dhs.gov
my_datastore: Trusted Datastore Cluster (AJ)