---
_hosts: '{{ my_vct_servername }}'
my_cluster: ajssprdlpesx80.cvp.cs
my_folder: Linux/TIM/PRD
my_datacenter: AJ PROD
my_hostname: "{{ my_vct_servername | lower }}.{{ my_dns_domain }}"
my_network_name: VM - TIM Restricted (126) (LACP)
my_netmask: 255.255.254.0
my_gateway_address: 10.0.126.1
my_dnsserver1: 10.0.8.129
my_dnsserver2: 10.0.8.132
my_dns_domain: cvp.cs
my_datastore: Restricted Datastore Cluster (AJ)
my_template: RHEL89_CRED_Template_Restricted