# Destination vCenter details
vcenter_hostname: "198.51.100.20"
vcenter_username: "automation-svc"
vcenter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          EXAMPLE_ENCRYPTED_VALUE_REDACTED_FOR_PUBLIC_REPOSITORY
dest_datacenter: "AJ NON-PROD"
dest_datastore: "Trusted Datastore Cluster (AJ)"
dest_folder: "/AJ NON-PROD/vm/Automation/Templates"
dest_cluster: "cluster01.example.com"
export_path: "/tmp"  # Path where the OVF/OVA will be exported