source_vcenter_hostname: "198.51.100.10"
source_vcenter_username: "automation-svc"
source_vcenter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          EXAMPLE_ENCRYPTED_VALUE_REDACTED_FOR_PUBLIC_REPOSITORY
source_datacenter: "CS NON-PROD"

export_path: "/tmp"  # Path where the OVF/OVA will be exported

# Destination vCenter details
dest_vcenter_hostname: "198.51.100.20"
dest_vcenter_username: "automation-svc"
dest_vcenter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          EXAMPLE_ENCRYPTED_VALUE_REDACTED_FOR_PUBLIC_REPOSITORY
dest_datacenter: "AJ NON-PROD"
dest_datastore: "Trusted Datastore Cluster (AJ)"
dest_folder: "/AJ NON-PROD/vm/Automation/Templates"
dest_cluster: "cluster01.example.com"

##
ajprd_vcenter_hostname: 198.51.100.20
prd_vcenter_username: automation-svc
prd_vcenter_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          EXAMPLE_ENCRYPTED_VALUE_REDACTED_FOR_PUBLIC_REPOSITORY
ajprd_datacenter: AJ PRD
aj_trusted_datastore: Trusted Datastore Cluster (AJ)
ajprd_dest_folder: "/AJ PRD/vm/Automation/Templates"
ajprd_trusted_cluster: cluster02.example.com
ajprd_restricted_cluster: cluster03.example.com
aj_restricted_datastore: Restricted Datastore Cluster (AJ)

##
csprd_vcenter_hostname: 198.51.100.10
csprd_datacenter: CS PRD
cs_trusted_datastore: Trusted Datastore Cluster (CS)
csprd_dest_folder: "/CS PRD/vm/Automation/Templates"
csprd_trusted_cluster: cluster04.example.com
csprd_restricted_cluster: cluster05.example.com
cs_restricted_datastore: Restricted Datastore Cluster (CS)