---
- name: Get Datacenter Information
  ansible.builtin.include_role:
    name: GetDatacenterInfo
  when: my_datacenter is not defined

- name: Run only if the VMLOCATION matches my_datacenter
  debug:
    msg: "Skipping this vcenter server"
  when: VMLOCATION != my_datacenter

- name: Running main play
  block:
  - name: Get Host UUID Information
    ansible.builtin.include_role:
      name: GetHostInfo
    when: my_vct_servername_uuid is not defined

  - name: "Renaming my_vct_servername to new_vct_servername"
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname | default(omit) }}" 
      username: "{{ vcenter_username | default(omit) }}"
      password: "{{ vcenter_password | default(omit) }}"
      uuid: "{{ my_vct_servername_uuid }}"
      name: "{{ new_vct_servername }}"
      folder: "{{ my_folder }}"
    delegate_to: localhost
  
  when: VMLOCATION == my_datacenter and new_vct_servername is defined and areyousure_deletevm != 'yes'