---
# vars file for QAChecklist
needsAreboot: "No Reboot is required"
needsPatches: "YES"
needsSplunk:  "YES"
needsMcafee:  "YES"
needsTanium:  "YES"
needsFlexera: "YES"
needsChrony:  "YES"
needsPostfix: "YES"
needsPuppet:  "YES"
needsPassSet: "YES"
needsSNMP:    "YES"
needsSSSD:    "YES"
needsTstuser: "YES"
nameserver1:  "NEEDS ATTENTION"
nameserver2:  "NEEDS ATTENTION"
nameserver3:  "NEEDS ATTENTION"
lookup:       "NEEDS ATTENTION"
